In [37]:
import pandas as pd
import os
from tqdm import tqdm
import geopandas as gpd

In [133]:
output_path = r"D:\qing_research\1_flood_water\1_flood_water_network\data\repair\by_dma"
repair_path = r"D:\qing_research\1_flood_water\1_flood_water_network\data\repair\Repairs.xlsx"
DMA_mapping_path = r"D:\qing_research\1_flood_water\1_flood_water_network\data\Anglian_water\processed\DMA_Mapping.csv"
flood_2020_path = r"D:\qing_research\1_flood_water\1_flood_water_network\data\Geo\flood\2_extract_flood_date_waterflow\2020\flood_shp_2020.shp"
flood_2023_path = r"D:\qing_research\1_flood_water\1_flood_water_network\data\Geo\flood\2_extract_flood_date_waterflow\2023\flood_shp_2023.shp"
flood_2024_path = r"D:\qing_research\1_flood_water\1_flood_water_network\data\Geo\flood\2_extract_flood_date_waterflow\2024\flood_shp_2024.shp"

In [134]:
DMA_mapping = pd.read_csv(DMA_mapping_path)
repair_data = pd.read_excel(repair_path)
flood_2020 = gpd.read_file(flood_2020_path)
flood_2023 = gpd.read_file(flood_2023_path)
flood_2024 = gpd.read_file(flood_2024_path)

In [135]:
repair_data.drop(columns = ['Order NO','Unnamed: 2','Unnamed: 18','Unnamed: 19', 'Unnamed: 20','Day','Week', 'Month', 'Year'],inplace = True)
repair_data['repair_id'] = range(1,len(repair_data)+1)
repair_data = repair_data.merge(DMA_mapping, left_on='DMA', right_on='DMA_Name', how='left')
repair_data.drop(columns = ['DMA_Name','x_coord','y_coord'],inplace = True)

In [108]:
repair_data['Basic Start Date'] = pd.to_datetime(repair_data['Basic Start Date'])

In [136]:
floods_date_2020 = flood_2020.groupby(['start_date', 'end_date']).size().reset_index(name='counts_date')

In [137]:
floods_date_2020['start_date'] = pd.to_datetime(floods_date_2020['start_date'])
floods_date_2020['end_date'] = pd.to_datetime(floods_date_2020['end_date'])
floods_date_2020['expanded_startdate'] = floods_date_2020['start_date'] - pd.Timedelta(days = 7)
floods_date_2020['expanded_enddate'] = floods_date_2020['end_date'] + pd.Timedelta(days = 14)

In [141]:
flood_with_repair = []
for _,date_row in floods_date_2020.iterrows():
    start = date_row['expanded_startdate']
    end = date_row['expanded_enddate']
    flood_repair = repair_data[(repair_data['Basic Start Date']>=start)&(repair_data['Basic Start Date']<=end)]
    flood_with_repair.append(flood_repair)

In [139]:
all_repair_flood_2020 = pd.concat(flood_with_repair, ignore_index=True)
all_repair_flood_2020 = all_repair_flood_2020.drop_duplicates()
print(len(all_repair_flood_2020))

1892

In [142]:
floods_date_2023 = flood_2023.groupby(['start_date', 'end_date']).size().reset_index(name='counts_date')

In [143]:
floods_date_2023['start_date'] = pd.to_datetime(floods_date_2023['start_date'])
floods_date_2023['end_date'] = pd.to_datetime(floods_date_2023['end_date'])
floods_date_2023['expanded_startdate'] = floods_date_2023['start_date'] - pd.Timedelta(days = 7)
floods_date_2023['expanded_enddate'] = floods_date_2023['end_date'] + pd.Timedelta(days = 14)

In [144]:
flood_with_repair = []
for _,date_row in floods_date_2023.iterrows():
    start = date_row['expanded_startdate']
    end = date_row['expanded_enddate']
    flood_repair = repair_data[(repair_data['Basic Start Date']>=start)&(repair_data['Basic Start Date']<=end)]
    flood_with_repair.append(flood_repair)

In [145]:
all_repair_flood_2023 = pd.concat(flood_with_repair, ignore_index=True)
all_repair_flood_2023 = all_repair_flood_2023.drop_duplicates()
print(len(all_repair_flood_2023))

1467

In [147]:
floods_date_2024 = flood_2024.groupby(['start_date', 'end_date']).size().reset_index(name='counts_date')

In [148]:
floods_date_2024['start_date'] = pd.to_datetime(floods_date_2024['start_date'])
floods_date_2024['end_date'] = pd.to_datetime(floods_date_2024['end_date'])
floods_date_2024['expanded_startdate'] = floods_date_2024['start_date'] - pd.Timedelta(days = 7)
floods_date_2024['expanded_enddate'] = floods_date_2024['end_date'] + pd.Timedelta(days = 14)

In [150]:
flood_with_repair = []
for _,date_row in floods_date_2024.iterrows():
    start = date_row['expanded_startdate']
    end = date_row['expanded_enddate']
    flood_repair = repair_data[(repair_data['Basic Start Date']>=start)&(repair_data['Basic Start Date']<=end)]
    flood_with_repair.append(flood_repair)

In [151]:
all_repair_flood_2024 = pd.concat(flood_with_repair, ignore_index=True)
all_repair_flood_2024 = all_repair_flood_2024.drop_duplicates()
print(len(all_repair_flood_2024))

1923

In [ ]:
output_dir = r"D:\qing_research\1_flood_water\1_flood_water_network\data\Geo\flood\2_extract_flood_date_waterflow"

In [ ]:
for _, flood_row in tqdm(flood_2020.iterrows(),total=len(flood_2020)):
    dma_ids = flood_row['DMA_ids']
    for dma_id in dma_ids:
        dma_ids_repair = all_repair_flood_2020['DMA_ID'].dropna().astype(int).tolist()  # Ensure consistent types
        exists = any(dma_id in dma_ids_repair for dma_id in dma_ids_flood)
        if exists:
            output_file_name = f"flood_{flood_row['flood_id']}_{flood_row['start_date'].strftime('%Y%m%d')}_{flood_row['end_date'].strftime('%Y%m%d')}_{dma_id}.csv"
            output_path = os.path.join(output_dir,output_file_name)
            data = pd.read_csv(output_path)
            data['repair'] = 1 when data['Date_Time'] =

In [162]:
flood_2020

,name,start_date,end_date,flood_src,flood_caus,data_src,fluvial_f,coastal_f,tidal_f,flood_id,DMA_ids,geometry
0,2020 February Flood Incident - Storm Ciara,2020-02-08,2020-02-14,main river,channel capacity exceeded (no raised defences),Satellite - Radar,True,False,False,8,[579],"POLYGON Z ((-110913.298 7064453.303 0, -110929..."
1,2020 February Flood Incident - Storm Ciara,2020-02-08,2020-02-14,main river,channel capacity exceeded (no raised defences),Satellite - Radar,True,False,False,59,[579],"MULTIPOLYGON Z (((-112400.716 7063479.888 0, -..."
2,LNA_2020_02_River Witham,2020-02-16,2020-02-24,main river,overtopping of defences,Visual,True,False,False,228,"[381, 14, 1046]","MULTIPOLYGON Z (((-83865.128 6981726.578 0, -8..."
3,LNA_2020_02_River Witham,2020-02-16,2020-02-24,main river,overtopping of defences,Visual,True,False,False,229,"[381, 14, 1046]","MULTIPOLYGON Z (((-82616.734 6980900.966 0, -8..."
4,River Waveney Flooding 2020,2020-12-23,2020-12-30,main river,channel capacity exceeded (no raised defences),Satellite - Optical,True,False,False,328,"[940, 502, 941]","MULTIPOLYGON Z (((112285.451 6868380.189 0, 11..."
5,LNA_2020_December_Southwick Brook,2020-12-23,2020-12-24,main river,channel capacity exceeded (no raised defences),Visual,True,False,False,329,"[473, 1586]","POLYGON Z ((-55793.647 6894125.628 0, -55781.3..."
6,LNA_2020_December_Harpers Brook_Sudborough,2020-12-23,2020-12-24,main river,channel capacity exceeded (no raised defences),Visual,True,False,False,330,[1885],"POLYGON Z ((-64960.158 6877934.908 0, -64950.4..."
7,LNA_2020_December_Harpers Brook_Brigstock,2020-12-23,2020-12-24,main river,channel capacity exceeded (no raised defences),Visual,True,False,False,331,[266],"MULTIPOLYGON Z (((-67961.415 6883426.326 0, -6..."
8,LNA_2020_December_Harpers Brook_Brigstock,2020-12-23,2020-12-24,drainage,local drainage/surface water,Other,False,False,False,332,[266],"POLYGON Z ((-67655.038 6882969.348 0, -67675.8..."
9,LNA_2020_December_Wootton Brook_Collingtree Park,2020-12-23,2020-12-23,main river,channel capacity exceeded (no raised defences),Visual,True,False,False,333,[2004],"POLYGON Z ((-100685.782 6836592.814 0, -100642..."
10,LNA_2020_December_Slade Brook_Kettering,2020-12-23,2020-12-24,main river,channel capacity exceeded (no raised defences),Visual,True,False,False,334,[982],"MULTIPOLYGON Z (((-79398.797 6868349.226 0, -7..."
11,LNA_2020_December_Wootton Brook_Collingtree Park,2020-12-23,2020-12-23,ordinary watercourse,channel capacity exceeded (no raised defences),Other,True,False,False,335,[2004],"POLYGON Z ((-100793.149 6836541.622 0, -100794..."
12,LNA_2020_December_Wootton Brook_Collingtree Park,2020-12-23,2020-12-23,unknown,unknown,Other,False,False,False,336,[2004],"POLYGON Z ((-100555.213 6836349.422 0, -100574..."

In [155]:
repair_dma_2020 = all_repair_flood_2020.groupby(['DMA_ID']).size().reset_index(name='counts_repair')
repair_dma_2020 = repair_dma_2020.sort_values(by='counts_repair', ascending=False)

In [157]:
repair_dma_2023 = all_repair_flood_2023.groupby(['DMA_ID']).size().reset_index(name='counts_repair')
repair_dma_2023 = repair_dma_2023.sort_values(by='counts_repair', ascending=False)

In [158]:
repair_dma_2024 = all_repair_flood_2024.groupby(['DMA_ID']).size().reset_index(name='counts_repair')
repair_dma_2024 = repair_dma_2024.sort_values(by='counts_repair', ascending=False)

In [140]:
floods_date_2020

  start_date   end_date  counts_date expanded_startdate expanded_enddate
0 2020-02-08 2020-02-14            2         2020-02-01       2020-02-28
1 2020-02-16 2020-02-24            2         2020-02-09       2020-03-09
2 2020-12-23 2020-12-23            3         2020-12-16       2021-01-06
3 2020-12-23 2020-12-24            5         2020-12-16       2021-01-07
4 2020-12-23 2020-12-30            1         2020-12-16       2021-01-13

In [131]:
all_repair_flood_2020

,DMA,Proactive ~ Reactive,TUP,FinishDate,Basic Start Date,Start Constraint Date,Repair Time days,Whole LIfe Days,Network Area,Area,Coding Code,Leakage,repair_id,DMA_ID
0,BRASWSMA,Proactive,NW T31 Stop Tap Replacement with Boundary Box,2021-03-26,2020-02-05,2021-02-15,40.0,416.0,Ipswich,East,WLPK,Leakage,842,237.0
1,CLAYWLMA,Proactive,NW T31 Stop Tap Replacement with Boundary Box,2020-04-09,2020-02-06,2020-02-11,59.0,64.0,Ipswich,East,WLPK,Leakage,843,NaN
2,HIOAK1MA,Proactive,NW T31 Stop Tap Replacement with Boundary Box,2020-04-16,2020-02-04,2020-02-05,72.0,73.0,Norwich,East,WLPK,Leakage,846,826.0
3,HILGAYMA,Reactive,NW T31 Stop Tap Replacement with Boundary Box,2020-04-07,2020-02-11,2020-03-16,23.0,57.0,Kings Lynn,East,WLEK,Leakage,847,822.0
4,THETLOMA,Proactive,NW T31 Stop Tap Replacement with Boundary Box,2020-10-28,2020-02-13,2020-10-23,6.0,259.0,Kings Lynn,East,WLPK,Leakage,848,1774.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4154,SPEASTMA,Reactive,NW T38 Mains Fitting,2021-01-13,2021-01-08,2021-01-08,6.0,6.0,Grantham,North,WLLV,Leakage,125323,1589.0
4155,BUCKWAMA,Proactive,NW T38 Mains Fitting,2021-03-05,2021-01-11,2021-01-19,46.0,54.0,Milton Keynes,South,WLL4,Leakage,125324,302.0
4156,COTTNGMA,Reactive,NW T38 Mains Fitting,2021-01-15,2021-01-12,2021-01-12,4.0,4.0,Northampton,South,WLLV,Leakage,125325,430.0
4157,OLDLESMA,Reactive,NW T38 Mains Fitting,2021-02-01,2021-01-12,2021-01-13,20.0,21.0,Grantham,North,WLLV,Leakage,125326,1330.0
4158,BILLRDMA,Proactive,NW T38 Mains Fitting,2021-01-27,2021-01-13,2021-01-21,7.0,15.0,Milton Keynes,South,WLL4,Leakage,125327,129.0

In [146]:
all_repair_flood_2023

,DMA,Proactive ~ Reactive,TUP,FinishDate,Basic Start Date,Start Constraint Date,Repair Time days,Whole LIfe Days,Network Area,Area,Coding Code,Leakage,repair_id,DMA_ID
0,SWISBXMA,Reactive,NW T31 Stop Tap Replacement with Boundary Box,2023-03-21,2023-10-17,2022-11-03,139.0,-209.0,Kings Lynn,East,WLEB,Leakage,21678,1752.0
1,CHEASHMA,Proactive,NW T31 Stop Tap Replacement with Boundary Box,2023-11-10,2023-10-23,2023-11-01,9.0,19.0,Kings Lynn,East,WLL4,Leakage,23707,NaN
2,BRABOOMA,Reactive,NW T31 Stop Tap Replacement with Boundary Box,2023-10-03,2023-10-26,2023-06-27,52.0,-22.0,Kings Lynn,East,WLVT,Leakage,25706,196.0
3,COLLYBMA,Reactive,NW T31 Stop Tap Replacement with Boundary Box,2023-11-07,2023-10-13,2023-10-20,18.0,26.0,Ipswich,East,WLEB,Leakage,28996,409.0
4,COLMSIMA,Reactive,NW T31 Stop Tap Replacement with Boundary Box,2023-12-08,2023-10-13,2023-10-24,45.0,57.0,Ipswich,East,WLEB,Leakage,28997,411.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1462,LACEBYMA,Proactive,NW T38 Mains Fitting,2023-11-13,2023-11-02,2023-11-06,7.0,12.0,Grimsby,North,WLL4,Leakage,126777,999.0
1463,GOSBERMA,Reactive,NW T38 Mains Fitting,2023-11-03,2023-11-03,2023-11-03,0.0,1.0,Grantham,North,WLLV,Leakage,126778,688.0
1464,SUTBOSMA,Reactive,NW T38 Mains Fitting,2023-11-07,2023-11-03,2023-11-03,4.0,5.0,Grantham,North,WLLV,Leakage,126779,1729.0
1465,LACEBYMA,Reactive,NW T38 Mains Fitting,2023-11-14,2023-11-03,2023-11-06,8.0,12.0,Grimsby,North,WLVT,Leakage,126780,999.0
1466,WASHBYMA,Proactive,NW T38 Mains Fitting,2023-11-14,2023-11-06,2023-11-06,8.0,9.0,Grimsby,North,WLL4,Leakage,126781,1869.0

In [152]:
all_repair_flood_2024

,DMA,Proactive ~ Reactive,TUP,FinishDate,Basic Start Date,Start Constraint Date,Repair Time days,Whole LIfe Days,Network Area,Area,Coding Code,Leakage,repair_id,DMA_ID
0,BRAPRNMA,Proactive,NW T31 Stop Tap Replacement with Boundary Box,2023-10-20,2024-01-17,2023-08-18,63.0,-88.0,Ipswich,East,WLL4,Leakage,23791,231.0
1,TOPPESMA,Reactive,NW T31 Stop Tap Replacement with Boundary Box,2023-12-04,2024-01-16,2023-04-13,235.0,-42.0,Ipswich,East,WLEK,Leakage,23829,1814.0
2,SUDBCTMA,Reactive,NW T31 Stop Tap Replacement with Boundary Box,2023-12-11,2024-01-23,2023-08-21,112.0,-42.0,Ipswich,East,WLVT,Leakage,27347,1686.0
3,HARLS1MA,Reactive,NW T31 Stop Tap Replacement with Boundary Box,2023-10-25,2024-01-18,2023-09-27,28.0,-84.0,Norwich,East,WLEK,Leakage,28228,788.0
4,SUDCCRMA,Reactive,NW T31 Stop Tap Replacement with Boundary Box,2023-11-27,2024-01-18,2023-10-09,49.0,-51.0,Ipswich,East,WLVT,Leakage,28847,1690.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1918,RETCENMA,Reactive,NW T38 Mains Fitting,2024-07-01,2024-01-18,2024-06-18,14.0,166.0,Lincoln,North,WLLV,Leakage,126838,1427.0
1919,MOORRDMA,Reactive,NW T38 Mains Fitting,2024-02-06,2024-01-18,2024-01-23,14.0,20.0,Grimsby,North,WLVT,Leakage,126839,1152.0
1920,PETSTKMA,Reactive,NW T38 Mains Fitting,2024-01-31,2024-01-19,2024-01-24,7.0,13.0,Grantham,North,WLLV,Leakage,126840,1369.0
1921,BTOWNCMA,Reactive,NW T38 Mains Fitting,2024-02-14,2024-01-20,2024-02-12,2.0,26.0,Milton Keynes,South,WLLV,Leakage,126841,291.0
1922,KEYSOEMA,Proactive,NW T38 Mains Fitting,2024-05-28,2024-01-23,2024-02-05,114.0,127.0,Milton Keynes,South,WLL5,Leakage,126842,952.0

In [156]:
repair_dma_2020

     DMA_ID  counts_repair
408  1023.0             17
46    124.0             11
540  1361.0             11
3       6.0             11
451  1126.0             11
..      ...            ...
326   817.0              1
323   813.0              1
322   811.0              1
321   809.0              1
786  2030.0              1

[787 rows x 2 columns]

In [159]:
repair_dma_2023

     DMA_ID  counts_repair
435  1283.0             30
25     73.0             25
82    223.0             15
568  1668.0             13
539  1570.0             13
..      ...            ...
330   969.0              1
328   959.0              1
327   947.0              1
325   943.0              1
345  1013.0              1

[691 rows x 2 columns]

In [160]:
repair_dma_2024

     DMA_ID  counts_repair
180   449.0             12
648  1590.0             12
692  1694.0             12
598  1462.0             12
514  1265.0             11
..      ...            ...
124   277.0              1
436  1083.0              1
433  1080.0              1
432  1079.0              1
0       1.0              1

[815 rows x 2 columns]

In [161]:
flood_2020

,name,start_date,end_date,flood_src,flood_caus,data_src,fluvial_f,coastal_f,tidal_f,flood_id,DMA_ids,geometry
0,2020 February Flood Incident - Storm Ciara,2020-02-08,2020-02-14,main river,channel capacity exceeded (no raised defences),Satellite - Radar,True,False,False,8,[579],"POLYGON Z ((-110913.298 7064453.303 0, -110929..."
1,2020 February Flood Incident - Storm Ciara,2020-02-08,2020-02-14,main river,channel capacity exceeded (no raised defences),Satellite - Radar,True,False,False,59,[579],"MULTIPOLYGON Z (((-112400.716 7063479.888 0, -..."
2,LNA_2020_02_River Witham,2020-02-16,2020-02-24,main river,overtopping of defences,Visual,True,False,False,228,"[381, 14, 1046]","MULTIPOLYGON Z (((-83865.128 6981726.578 0, -8..."
3,LNA_2020_02_River Witham,2020-02-16,2020-02-24,main river,overtopping of defences,Visual,True,False,False,229,"[381, 14, 1046]","MULTIPOLYGON Z (((-82616.734 6980900.966 0, -8..."
4,River Waveney Flooding 2020,2020-12-23,2020-12-30,main river,channel capacity exceeded (no raised defences),Satellite - Optical,True,False,False,328,"[940, 502, 941]","MULTIPOLYGON Z (((112285.451 6868380.189 0, 11..."
5,LNA_2020_December_Southwick Brook,2020-12-23,2020-12-24,main river,channel capacity exceeded (no raised defences),Visual,True,False,False,329,"[473, 1586]","POLYGON Z ((-55793.647 6894125.628 0, -55781.3..."
6,LNA_2020_December_Harpers Brook_Sudborough,2020-12-23,2020-12-24,main river,channel capacity exceeded (no raised defences),Visual,True,False,False,330,[1885],"POLYGON Z ((-64960.158 6877934.908 0, -64950.4..."
7,LNA_2020_December_Harpers Brook_Brigstock,2020-12-23,2020-12-24,main river,channel capacity exceeded (no raised defences),Visual,True,False,False,331,[266],"MULTIPOLYGON Z (((-67961.415 6883426.326 0, -6..."
8,LNA_2020_December_Harpers Brook_Brigstock,2020-12-23,2020-12-24,drainage,local drainage/surface water,Other,False,False,False,332,[266],"POLYGON Z ((-67655.038 6882969.348 0, -67675.8..."
9,LNA_2020_December_Wootton Brook_Collingtree Park,2020-12-23,2020-12-23,main river,channel capacity exceeded (no raised defences),Visual,True,False,False,333,[2004],"POLYGON Z ((-100685.782 6836592.814 0, -100642..."
10,LNA_2020_December_Slade Brook_Kettering,2020-12-23,2020-12-24,main river,channel capacity exceeded (no raised defences),Visual,True,False,False,334,[982],"MULTIPOLYGON Z (((-79398.797 6868349.226 0, -7..."
11,LNA_2020_December_Wootton Brook_Collingtree Park,2020-12-23,2020-12-23,ordinary watercourse,channel capacity exceeded (no raised defences),Other,True,False,False,335,[2004],"POLYGON Z ((-100793.149 6836541.622 0, -100794..."
12,LNA_2020_December_Wootton Brook_Collingtree Park,2020-12-23,2020-12-23,unknown,unknown,Other,False,False,False,336,[2004],"POLYGON Z ((-100555.213 6836349.422 0, -100574..."